cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5
cp /home/soleary/GAFFTOPS/BMA_POPGEN/scr/idxstats.sh /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6
