samtools idxstats	data/SEQ/BMA-1/BMA_1A-A01_00888-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A02_00887-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A03_00886-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A04_00885bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A05_00884-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A06_00883-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A07_00882-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A08_00881-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A09_FLG-33-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A10_BB-17-036-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A11_BM9-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-A12_BM17-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B01_CS-01-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B02_CS-25-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B03_CS-03-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B04_CS-04-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B05_CS-05-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B06_CS-06-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B07_CS-07-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B08_CS-08-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B09_CS-26-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B10_CS-27-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B11_CS-28-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-B12_CS-12-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C01_CCGN-001-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C02_CCGN-002-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C03_CCGN-003-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C04_CCGN-004-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C06_811-001-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C07_811-002-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C08_811-003-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C09_811-004-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C10_811-006-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C11_811-007-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-C12_811-008-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-D01_BM15-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-D02_CCGN01-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E01_BM001-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E02_BM002-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E03_BM003-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E04_BM004-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E05_BM008-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E07_BM044-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E08_BM080-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E10_BM092-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E11_BM103-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-E12_BM111-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F02_FLG-02-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F03_FLG-05-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F04_FLG-08-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F05_FLG-23-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F06_FLG-25-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F07_FLG-27-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F08_FLG-28-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F09_FLG-29-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F10_FLG-31-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-F11_FLG-32-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G01_BB-17-020-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G03_BB-17-027-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G04_BB-17-029-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G05_BB-17-032-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G06_BB-17-034-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G07_BB-17-035-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G09_BB-17-047-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G10_BB-17-048-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G11_BB-17-109-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-G12_BB-17-111-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-H01_BM81-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-H02_MS18-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-H03_CC02-08-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1A-H04_CC02-35-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A01_00816-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A02_00815-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A03_00814-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A04_00813-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A05_00812-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A06_00880-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A07_00887-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A08_00818-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A09_00817-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A10_00811-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A11_00810-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-A12_00809-bma-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B01_LA-001-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B02_LA-003-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B03_LA-014-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B04_LA-049-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B05_LA-050-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B06_LA-062-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B07_LA-073-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B08_LA-083-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B09_LA-127-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B10_LA-128-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B11_LA-129-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-B12_LA-130-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C01_MS-18-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C02_MS-19-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C03_MS-20-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C04_MS-21-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C05_MS-22-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C06_MS-23-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C07_MS-51-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C08_MS-52-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C09_MS-53-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C10_MS-54-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C11_MS-55-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-C12_MS-56-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-D01_CC-26-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-D02_CC-29-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E01_MB-01-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E02_MB-02-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E03_MB-03-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E04_MB-04-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E05_MB-05-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E06_MB-06-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E07_MB-07-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E08_MB-08-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E09_MB-09-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E10_MB-10-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E11_MB-11-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-E12_MB-12-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F01_CS-13-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F02_CS-14-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F03_CS-15-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F04_CS-16-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F05_CS-17-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F06_CS-18-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F07_CS-19-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F08_CS-20-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F09_CS-21-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F10_CS-22-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F11_CS-23-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-F12_CS-24-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G01_811-009-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G02_811-010-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G03_811-011-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G04_CC-01-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G05_CC-02-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G06_CC-03-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G07_CC-04-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G08_CC-05-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G09_CC-06-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G10_CC-07-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G11_CC-08-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-1/BMA_1B-G12_CC-09-RG.bam	>> data/SEQ/BMA1.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A01_00762-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A03_00760-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A05_00744-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A07_00732-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A08_00740-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A09_00737-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A11_00735-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-A12_00733-bma-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B02_MB-13-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B03_OP040417GN02-3-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B04_OP040417GN02-7-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B05_MB-14-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B06_MB-15-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B07_MB-16-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B08_MB-17-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B09_MB-18-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B10_MB-19-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B11_MB-20-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-B12_MB-21-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C01_MS-57-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C02_MS-58-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C03_MS-59-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C04_MS-60-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C05_MS-61-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C06_MS-62-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C07_MS-63-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C08_MS-01-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C09_MS-02-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C10_MS-03-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C11_MS-04-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-C12_MS-05-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D01_LA-004-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D02_LA-015-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D03_LA-016-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D04_LA-051-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D05_LA-063-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D06_LA-081-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-D07_BB-17-519-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-E01_LA-003-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-E06_LA-052-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-E08_LA-064-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-E09_LA-072-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-E10_LA-074-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-E12_LA-084-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F01_BB-17-112-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F02_BB-17-116-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F03_BB-17-118-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F04_BB-17-119-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F05_BB-17-120-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F06_BB-17-121-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F07_BB-17-123-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F08_BB-17-330-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F09_BB-17-493-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F10_BB-17-517-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-F11_BB-17-518-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G01_FLG-03-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G02_FLG-06-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G03_FLG-09-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G04_FLG-24-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G05_FLG-26-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G06_FLG-30-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G07_FLG-34-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G08_FLG-43-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G09_FLG-45-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G10_FLG-81-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-G11_FLG-88-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2A-H01_BB-17-140-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A01_BM005-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A02_BM010-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A04_BM018-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A05_BM024-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A06_BM025-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A07_BM026-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A08_BM072-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A09_BM083-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A10_BM091-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A11_BM101-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-A12_BM110-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B01_CC-12-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B02_CC-18-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B03_CC-19-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B04_CC-20-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B05_CC-21-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B06_CC-22-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B07_CC-27-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B08_CC-28-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B09_CC-35-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B11_CC-41-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-B12_CC-42-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C01_MB-22-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C02_MB-23-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C03_MB-24-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C04_MB-25-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C05_MB-26-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C06_MB-27-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C07_MB-28-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C08_MB-29-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C09_MB-30-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C10_MB-31-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-C11_MB-32-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-D01_LA-079-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E01_CC-11-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E02_CC-34-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E03_CC-38-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E04_CC-44-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E05_MB-34-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E06_MB-35-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E07_MB-36-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E08_MB-37-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E09_MB-38-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E10_MB-39-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E11_MB-40-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-E12_MB-41-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F01_MB-42-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F02_MB-43-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F03_MS-13-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F04_MS-14-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F05_MS-15-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F06_MS-16-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F07_MS-17-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F08_MS-30-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F09_MS-31-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F10_BB-17-141-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F11_BB-17-153-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-F12_BB-17-181-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G01_BB-17-183-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G02_BB-17-190-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G03_BB-17-192-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G04_BB-17-143-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G05_BMAR-03-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G06_FLG-12-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G07_FLG-14-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G08_FLG-36-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G09_FLG-44-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G10_FLG-47-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G11_FLG-71-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-G12_FLG-84-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-H01_CS3-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-2/BMA_2B-H02_MB06-RG.bam	>> data/SEQ/BMA2.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A01_CC-17-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A02_CC-12-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A03_CC-15-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A04_CC-46-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A05_CC-23-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A06_CC-24-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A09_CC-33-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A10_CC-37-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A11_CC-39-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-A12_CC-40-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B01_BM047-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B02_BM048-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B03_BM056-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B04_BM057-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B05_BM061-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B06_BM062-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B07_BM067-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B08_BM068-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B09_BM082-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B10_BM084-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B11_BM099-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-B12_BM100-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C01_FLG-46-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C02_FLG-48-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C03_FLG-49-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C04_FLG-50-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C05_FLG-59-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C06_FLG-60-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C07_FLG-61-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C08_FLG-62-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C09_FLG-82-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C10_FLG-83-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C11_FLG-85-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-C12_FLG-86-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-D01_BM006-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3A-D02_BM007-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A05_BM019-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A06_BM020-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A07_BM027-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A08_BM028-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A09_BM035-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A10_BM036-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A11_BM039-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-A12_BM040-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B02_FLG-07-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B03_FLG-10-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B04_FLG-11-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B05_FLG-16-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B06_FLG-17-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B07_FLG-18-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B08_FLG-19-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B09_FLG-35-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B10_FLG-37-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B11_FLG-38-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-B12_FLG-39-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C01_MS-06-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C02_MS-07-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C03_MS-08-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C04_MS-09-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C05_MS-10-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C06_MS-11-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C07_MS-24-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-C08_MS-25-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-D01_MS26-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-D02_BM15-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-D04_LA-058-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-D05_CC-43-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-D06_BM023-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E01_BB-17-520-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E01_MB-44-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E02_BB-17-521-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E02_MB-45-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E03_BB-17-522-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E03_MB-46-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E04_BB-17-523-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E04_MB-47-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E05_BB-17-524-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E05_MB-48-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E06_BB-17-142-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E06_MB-49-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E07_BB-17-144-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E07_MS-32-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E08_BB-17-168-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E08_MS-33-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E09_BB-17-177-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E09_MS-34-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E10_BB-17-184-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E10_MS-35-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E11_BB-17-193-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E11_MS-36-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E12_BMAR-02-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-E12_MS-37-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F01_BB-17-108-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F01_LA-005-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F02_LA-006-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F03_BB-17-150-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F03_LA-017-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F04_BB-17-156-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F04_LA-018-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F05_BMAR-04-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F05_LA-053-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F06_BMAR-05-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F06_LA-054-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F07_LA-065-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F08_LA-066-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F09_BM022-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F10_LA-082-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F11_BM054-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F11_LA-085-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F12_BM055-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-F12_LA-089-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G01_LA-010-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G01_LA-012-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G02_LA-011-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G02_LA-013-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G03_LA-020-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G03_LA-030-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G04_LA-021-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G04_LA-057-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G05_LA-055-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G06_LA-056-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G06_LA-071-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G07_LA-068-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G08_CC-45-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G08_LA-069-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G09_BM105-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G09_LA-076-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G10_BM106-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G10_LA-077-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G11_LA-098-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G11_MB-53-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G12_LA-099-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-G12_MB-54-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H01_LA27-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H02_MS26-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H02_MS-38-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H03_BM027-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H03_MS-28-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H04_MS-29-RG.bam	>> data/SEQ/BMA3.idxstats
samtools idxstats	data/SEQ/BMA-3/BMA_3B-H05_FLG-04-RG.bam	>> data/SEQ/BMA3.idxstats
