ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5
ln -s /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF_IND/*.fq.gz /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6
