mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5
mkdir /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6
