rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/*.seqs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/*.fastq
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/*.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/namelist
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/uniqCperindv
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/dDocent.runs
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/xxx*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/fastp*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/total*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/uniq.full.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/sort.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/rainbow*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/overlap.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/other*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/contig.*
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/logfiles/
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/logfiles/
