rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/*.cov.stats
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/*.cov.stats
