rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF10_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF2_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF3_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF4_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF5_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF6_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF7_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF8_6/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_1/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_2/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_3/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_4/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_5/*.fq.gz
rm /home/soleary/GAFFTOPS/BMA_POPGEN/data/REF/REF9_6/*.fq.gz
